name: child-flow
on:
  workflow_call:
    inputs:
      branch-to-build:
        description: "Branch to build"
        required: true
        type: string
jobs:
  ch-job:
    runs-on: ubuntu-latest
    steps:
      - name: ch-step
        run: echo "Hello, this is from child 1 workflow!"
      - name: branch name
        run: echo ${{ inputs.branch-to-build }}
        
