name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get current branch name
        id: branch-name
        run: echo "branch=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: my-step
        run: echo "Hello World!"
  display-win:
    runs-on: windows-latest
    steps:
      - name: display-step
        run: echo ""Ecevution policy "
  Build:
    needs: [ "my-job" ]
    uses: vengalamseshu/Jenkins-Zero-To-Hero/.github/workflows/child1.yml@main
    with:
      branch-to-build: ${{ env.branch }}
