name: hello-world
on: push
jobs:
  Build:
    uses: vengalamseshu/Jenkins-Zero-To-Hero/.github/workflows/child1.yml@main
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  display-win:
    runs-on: windows-latest
    steps:
      - name: display-step
        run: echo ""Ecevution policy "
