name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  display:
    runs-on: ubuntu-latest
    steps:
      - name: display-step
        run: echo "Hello Pilla..!!"

        
